language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - mint.isi.edu
  - 54.148.90.74
env:
  global:
  - secure: ure2FGCq/RxlDEnbE4J4MVrynahBbNhdD4PH4MHEI4PvUbbMemR3vsW7gZU7YYkyA9hxCst+XI1jcjg8VArSVLiWDOnuY2ZI+gnHmQPJicDTJEcWvjCxO+3yj2nGxxlqDylqneppld7KctMkhjERvbzFOckDRCaCCsfiW6Qx2Px+vuGn5jp3hT2UzP0y+nWUUcgjjW6/+EO9YPBgrK6P75N93OMNbqT+Mpo0m+gZrT5cRkByF6kriSafj6O0dX/tNL0P6oDYG0yo95dJhKZ0GBb8kEvAK+YkZft66YGrtGWU+4WiPZ9cHAtfEOz7ABGf4vYrgCHoUZptVNX/vvq+PuNVtRHCMYhXv4r3LXlwtZUPCOP7LRwMD4MT6rTi39OJKjdvT+4/kwOQNY5J5045YD2+NZOzea4wN/Fd7Fu3zFMfoYFeZ211qqWmw4vKbUcmiwos0NM+yMl9ocZYWhLD0We3knPLO6ohf05iB2duUFxlr7VTyhFP9xFVNZAvBX9Rd7/FTDruorVN6r+OnpvLI1HjoKR7WVGC4P9+TQwmFfAeNYxg6zeN3XrrLWh/cUd7hxBsGeZM9bHq8eq1ecJ/grB7mBQCOXM2ZWEHumtfKUikaJYuHXOgQnW2LuaqdoMoLLGNEqyKisANLmu1023HNaLxhpdDX2zJn7vYW574pvo=
  - secure: 0zWhYRpFqMJr2a5bKWTgjZDarC1YUb+UwLq2OxX92fuoenChMKW36xC7zvBYFRYUeapPHg4wIKsiC3Kkt4UMgpTTsXDWpHF5gfRsYtRzlAQlFFm1qqj7Vi1Ecv3DXOTJuZzk0D98eGt+ataUFPx1B8AHKn3fyAFp7qF/ok/rxNFZqfl8MZjyfk95gr9AVDkORXP5ee3gws2/2tMQ80Q8fiI5ozWTEnSVeg0N6mSdyc8JYHt86DphnD+Doc1eU1/0qg80woc1C+WapPs/nTCF4i6bFYnwfgP77+43WLwXdrcSB5xZSAfgqG+e6W43qBnvKYGihbVTGznhnexJjBxjtQtfQ6LXq6bP2SfH0M+wU+5ynGl/XayV9PwQkTngKOWTX+3DrLUgsY0y5HFdBbPvoSIVU9iZhucF5Wdb85hH8NREADWhmdiHU4e0JcgbNKNf53ElF4yTDQ6hfQ9CjsKI6VBmunu9OQr5Vd/uvp8XMzbs3PQ1RaxMN5iuxXMJdj5Qx0KFKUp1+ioQaeMMZ07MJGXPwIU0n1Y0emNcF7P18PTx8xGr6RuSUmK6S2JxGneQOodycct/N0AuJXBtrm5XT3hnnzHjQM1bgSd2bcyc19+DxZ0rqvkBgGRaqmK/Leo3z8RiwvYyiAkSLf/C8qOsGkVbmDlPNO9SPxkAG85jfaY=
install: yarn
cache: yarn
script: yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_b70b0c1c34e1_key -iv $encrypted_b70b0c1c34e1_iv
  -in google-api-key.ts.enc -out src/config/google-api-key.ts -d
before_deploy:
- echo $key_pass | gpg --passphrase-fd 0 id_travis_rsa.gpg
- eval "$(ssh-agent -s)"
- chmod 600 id_travis_rsa
- ssh-add id_travis_rsa
- mv build mint-ui-lit
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $TRAVIS_BUILD_DIR/mint-ui-lit mintui_$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|dev|enviroments)$"
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $TRAVIS_BUILD_DIR/mint-ui-lit mintui_$TRAVIS_TAG
  on:
    tags: true
    all_branches: true
